on:
    workflow_call:
        inputs:
            deploy:
                type: boolean
                description: "If true, the docs will be deployed."
                default: false

env:
  UV_FROZEN: "1"

jobs:
    run-docs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v6
        - name: Install uv and set the python version
          uses: astral-sh/setup-uv@v7
          with:
            python-version: "3.12"
            enable-cache: true
        - name: Install Python Dependencies
          run: uv sync --frozen --all-extras --all-packages
        - name: Build docs
          run: uv run --no-sync mkdocs build --verbose --clean
        - name: Build and push docs
          if: inputs.deploy
          run: uv run --no-sync mkdocs gh-deploy --force
